# 📘Домашнє завдання №8

**Лекція 16. Візуалізація за допомогою Matplotlib та Seaborn**

Виконав: **Bohdan Pinchuk**

Link: https://github.com/BogdanPinchuk/DataScience-PBY_HW8

Завантажте Titanic Dataset і побудуйте для вибраних змінних наступні графіки:

1. **Числові змінні** (`age`, `fare`)
  * **Histogram** — розподіл
  * **Box Plot** — виявлення викидів
  * **KDE Plot** — гладкий розподіл
  * **Violin Plot** — порівняння розподілу по класу чи статі
2. **Залежності між змінними**
  * **Scatter Plot** — `age` vs `fare` (кольором або розміром `survived`)
  * **Bubble Chart** — додати розмір точки по `sibsp` або `parch`
3. **Категоріальні змінні**
  * **Bar Chart** — кількість пасажирів за класами та статтю
  * **Pie Chart** — частка виживших по класах
  * **Lollipop Chart** — середній `fare` по класах
4. **Кореляція та взаємозв’язки**
  * **Heatmap** — кореляція числових змінних (`age`, `fare`, `sibsp`, `parch`)

In [25]:
# Download data (to cover the case when the data aren't accessible)

import shutil
import sqlite3
import pandas as pd
import seaborn as sns
from pathlib import Path
from IPython.display import display

# Input data
ds_name = "titanic"
db_file_name = "store_hw8.db"
git_project_url = "https://github.com/BogdanPinchuk/DataScience-PBY_HW8.git"
main_file_name = "Bohdan_Pinchuk_DS_HW8.ipynb"

# Solution
# global ds_data

# Note: to handle error: "SSL: CERTIFICATE_VERIFY_FAILED" or no connection to the server
try:
    # TODO: delete
    raise Exception
    ds_data = sns.load_dataset(ds_name)

    # Use only one time to initialize/update data (at first time)
    # conn = sqlite3.connect(db_file_name)
    # ds_data.to_sql(ds_name, conn, if_exists="replace", index=False)
    # conn.close()
except Exception:
    file_path = Path(db_file_name)

    if not file_path.exists():
        # upload all files
        current_path = !pwd
        current_path = current_path[0]
        parent_path = !dirname "$current_path"
        parent_path = parent_path[0]
        temp_path = f"{parent_path}/temp"

        # Clone data
        !rm -rf "$temp_path"
        !git clone "$git_project_url" "$temp_path"

        source = Path(temp_path)
        destination = Path(current_path)
        exclude = {main_file_name, ".git", ".idea"}

        for item in source.iterdir():
            if item.name in exclude:
                continue

            target = destination / item.name
            if item.is_dir():
                shutil.copytree(item, target, dirs_exist_ok=True)
            else:
                shutil.copy2(item, target)

        # Clean temp folder
        !rm -rf "$temp_path"

    conn = sqlite3.connect(db_file_name)
    ds_data = pd.read_sql(f"SELECT * FROM {ds_name}", conn)
    conn.close()

display(ds_data.head())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,1,NaN,Southampton,no,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,0,C,Cherbourg,yes,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,0,NaN,Southampton,yes,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,NaN,Southampton,no,1

In [28]:
import seaborn as sns

# Input data

# Solution
titanic = ds_data.copy()
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,1,NaN,Southampton,no,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,0,C,Cherbourg,yes,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,0,NaN,Southampton,yes,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,C,Southampton,yes,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,NaN,Southampton,no,1